---
# molecule/default/verify.yml
# Xác minh kết quả sau khi converge chạy xong
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Verify required packages are installed
      ansible.builtin.package:
        name:
          - curl
          - ca-certificates
          - jq
        state: present



    - name: Verify sysctl config file is written (99-k8s-sysbox.conf)
      ansible.builtin.stat:
        path: /etc/sysctl.d/99-k8s-sysbox.conf
      register: sysctl_config

    - name: Assert sysctl config exists
      ansible.builtin.assert:
        that:
          - sysctl_config.stat.exists


