---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - resourcequotas
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - lab.devops.toiyeuptit.com
  resources:
  - clusterlabs
  - instancelabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lab.devops.toiyeuptit.com
  resources:
  - clusterlabs/finalizers
  - instancelabs/finalizers
  verbs:
  - update
- apiGroups:
  - lab.devops.toiyeuptit.com
  resources:
  - clusterlabs/status
  - instancelabs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
