apiVersion: lab.devops.toiyeuptit.com/v1alpha1
kind: VirtualCluster
metadata:
  labels:
    app.kubernetes.io/name: typ-operator
    app.kubernetes.io/managed-by: kustomize
  name: virtualcluster-sample
spec:
  ttl: "4h"
  network:
    type: internal
  quota:
    compute:
      cpu:
        limit: "2"
      memory:
        limit: "4Gi"
    storage:
      limit: "30Gi"
    objects:
      podsLimit: 20
      servicesLimit: 10
