//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualCluster) DeepCopyInto(out *VirtualCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualCluster.
func (in *VirtualCluster) DeepCopy() *VirtualCluster {
	if in == nil {
		return nil
	}
	out := new(VirtualCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterComputeQuota) DeepCopyInto(out *VirtualClusterComputeQuota) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterComputeQuota.
func (in *VirtualClusterComputeQuota) DeepCopy() *VirtualClusterComputeQuota {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterComputeQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterComputeUsage) DeepCopyInto(out *VirtualClusterComputeUsage) {
	*out = *in
	out.CPUUsed = in.CPUUsed.DeepCopy()
	out.MemoryUsed = in.MemoryUsed.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterComputeUsage.
func (in *VirtualClusterComputeUsage) DeepCopy() *VirtualClusterComputeUsage {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterComputeUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterInstanceCount) DeepCopyInto(out *VirtualClusterInstanceCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterInstanceCount.
func (in *VirtualClusterInstanceCount) DeepCopy() *VirtualClusterInstanceCount {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterInstanceCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterList) DeepCopyInto(out *VirtualClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterList.
func (in *VirtualClusterList) DeepCopy() *VirtualClusterList {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterNetworkConfig) DeepCopyInto(out *VirtualClusterNetworkConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterNetworkConfig.
func (in *VirtualClusterNetworkConfig) DeepCopy() *VirtualClusterNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterObjectsQuota) DeepCopyInto(out *VirtualClusterObjectsQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterObjectsQuota.
func (in *VirtualClusterObjectsQuota) DeepCopy() *VirtualClusterObjectsQuota {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterObjectsQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterObjectsUsage) DeepCopyInto(out *VirtualClusterObjectsUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterObjectsUsage.
func (in *VirtualClusterObjectsUsage) DeepCopy() *VirtualClusterObjectsUsage {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterObjectsUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterQuotaConfig) DeepCopyInto(out *VirtualClusterQuotaConfig) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Compute.DeepCopyInto(&out.Compute)
	out.Objects = in.Objects
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterQuotaConfig.
func (in *VirtualClusterQuotaConfig) DeepCopy() *VirtualClusterQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterQuotaUsage) DeepCopyInto(out *VirtualClusterQuotaUsage) {
	*out = *in
	in.Compute.DeepCopyInto(&out.Compute)
	in.Storage.DeepCopyInto(&out.Storage)
	out.Objects = in.Objects
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterQuotaUsage.
func (in *VirtualClusterQuotaUsage) DeepCopy() *VirtualClusterQuotaUsage {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterQuotaUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterResourceLimit) DeepCopyInto(out *VirtualClusterResourceLimit) {
	*out = *in
	out.Limit = in.Limit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterResourceLimit.
func (in *VirtualClusterResourceLimit) DeepCopy() *VirtualClusterResourceLimit {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterResourceLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterSpec) DeepCopyInto(out *VirtualClusterSpec) {
	*out = *in
	out.Network = in.Network
	in.Quota.DeepCopyInto(&out.Quota)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterSpec.
func (in *VirtualClusterSpec) DeepCopy() *VirtualClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterStatus) DeepCopyInto(out *VirtualClusterStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	out.InstanceCount = in.InstanceCount
	in.QuotaUsage.DeepCopyInto(&out.QuotaUsage)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterStatus.
func (in *VirtualClusterStatus) DeepCopy() *VirtualClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterStorageQuota) DeepCopyInto(out *VirtualClusterStorageQuota) {
	*out = *in
	out.LocalLimit = in.LocalLimit.DeepCopy()
	out.NetworkLimit = in.NetworkLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterStorageQuota.
func (in *VirtualClusterStorageQuota) DeepCopy() *VirtualClusterStorageQuota {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterStorageQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualClusterStorageUsage) DeepCopyInto(out *VirtualClusterStorageUsage) {
	*out = *in
	out.LocalUsed = in.LocalUsed.DeepCopy()
	out.NetworkUsed = in.NetworkUsed.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualClusterStorageUsage.
func (in *VirtualClusterStorageUsage) DeepCopy() *VirtualClusterStorageUsage {
	if in == nil {
		return nil
	}
	out := new(VirtualClusterStorageUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstance) DeepCopyInto(out *VirtualInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstance.
func (in *VirtualInstance) DeepCopy() *VirtualInstance {
	if in == nil {
		return nil
	}
	out := new(VirtualInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceAccessEndpoint) DeepCopyInto(out *VirtualInstanceAccessEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceAccessEndpoint.
func (in *VirtualInstanceAccessEndpoint) DeepCopy() *VirtualInstanceAccessEndpoint {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceAccessEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceDataVolume) DeepCopyInto(out *VirtualInstanceDataVolume) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceDataVolume.
func (in *VirtualInstanceDataVolume) DeepCopy() *VirtualInstanceDataVolume {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceDataVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceList) DeepCopyInto(out *VirtualInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceList.
func (in *VirtualInstanceList) DeepCopy() *VirtualInstanceList {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstancePort) DeepCopyInto(out *VirtualInstancePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstancePort.
func (in *VirtualInstancePort) DeepCopy() *VirtualInstancePort {
	if in == nil {
		return nil
	}
	out := new(VirtualInstancePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceResourceLimit) DeepCopyInto(out *VirtualInstanceResourceLimit) {
	*out = *in
	out.Request = in.Request.DeepCopy()
	out.Limit = in.Limit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceResourceLimit.
func (in *VirtualInstanceResourceLimit) DeepCopy() *VirtualInstanceResourceLimit {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceResourceLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceResources) DeepCopyInto(out *VirtualInstanceResources) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
	in.EphemeralStorage.DeepCopyInto(&out.EphemeralStorage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceResources.
func (in *VirtualInstanceResources) DeepCopy() *VirtualInstanceResources {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceRootVolume) DeepCopyInto(out *VirtualInstanceRootVolume) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceRootVolume.
func (in *VirtualInstanceRootVolume) DeepCopy() *VirtualInstanceRootVolume {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceRootVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceSpec) DeepCopyInto(out *VirtualInstanceSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]VirtualInstancePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceSpec.
func (in *VirtualInstanceSpec) DeepCopy() *VirtualInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceStatus) DeepCopyInto(out *VirtualInstanceStatus) {
	*out = *in
	if in.AccessEndpoints != nil {
		in, out := &in.AccessEndpoints, &out.AccessEndpoints
		*out = make([]VirtualInstanceAccessEndpoint, len(*in))
		copy(*out, *in)
	}
	in.VolumesStatus.DeepCopyInto(&out.VolumesStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceStatus.
func (in *VirtualInstanceStatus) DeepCopy() *VirtualInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceStorage) DeepCopyInto(out *VirtualInstanceStorage) {
	*out = *in
	in.Root.DeepCopyInto(&out.Root)
	if in.DataVolumes != nil {
		in, out := &in.DataVolumes, &out.DataVolumes
		*out = make([]VirtualInstanceDataVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceStorage.
func (in *VirtualInstanceStorage) DeepCopy() *VirtualInstanceStorage {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceVolumeStatusDetail) DeepCopyInto(out *VirtualInstanceVolumeStatusDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceVolumeStatusDetail.
func (in *VirtualInstanceVolumeStatusDetail) DeepCopy() *VirtualInstanceVolumeStatusDetail {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceVolumeStatusDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualInstanceVolumesStatus) DeepCopyInto(out *VirtualInstanceVolumesStatus) {
	*out = *in
	out.RootVolume = in.RootVolume
	if in.DataVolumes != nil {
		in, out := &in.DataVolumes, &out.DataVolumes
		*out = make([]VirtualInstanceVolumeStatusDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualInstanceVolumesStatus.
func (in *VirtualInstanceVolumesStatus) DeepCopy() *VirtualInstanceVolumesStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualInstanceVolumesStatus)
	in.DeepCopyInto(out)
	return out
}
