//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLab) DeepCopyInto(out *ClusterLab) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLab.
func (in *ClusterLab) DeepCopy() *ClusterLab {
	if in == nil {
		return nil
	}
	out := new(ClusterLab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterLab) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabComputeQuota) DeepCopyInto(out *ClusterLabComputeQuota) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabComputeQuota.
func (in *ClusterLabComputeQuota) DeepCopy() *ClusterLabComputeQuota {
	if in == nil {
		return nil
	}
	out := new(ClusterLabComputeQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabComputeUsage) DeepCopyInto(out *ClusterLabComputeUsage) {
	*out = *in
	out.CPUUsed = in.CPUUsed.DeepCopy()
	out.MemoryUsed = in.MemoryUsed.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabComputeUsage.
func (in *ClusterLabComputeUsage) DeepCopy() *ClusterLabComputeUsage {
	if in == nil {
		return nil
	}
	out := new(ClusterLabComputeUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabInstanceCount) DeepCopyInto(out *ClusterLabInstanceCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabInstanceCount.
func (in *ClusterLabInstanceCount) DeepCopy() *ClusterLabInstanceCount {
	if in == nil {
		return nil
	}
	out := new(ClusterLabInstanceCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabList) DeepCopyInto(out *ClusterLabList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterLab, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabList.
func (in *ClusterLabList) DeepCopy() *ClusterLabList {
	if in == nil {
		return nil
	}
	out := new(ClusterLabList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterLabList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabNetworkConfig) DeepCopyInto(out *ClusterLabNetworkConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabNetworkConfig.
func (in *ClusterLabNetworkConfig) DeepCopy() *ClusterLabNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterLabNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabObjectsQuota) DeepCopyInto(out *ClusterLabObjectsQuota) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabObjectsQuota.
func (in *ClusterLabObjectsQuota) DeepCopy() *ClusterLabObjectsQuota {
	if in == nil {
		return nil
	}
	out := new(ClusterLabObjectsQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabObjectsUsage) DeepCopyInto(out *ClusterLabObjectsUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabObjectsUsage.
func (in *ClusterLabObjectsUsage) DeepCopy() *ClusterLabObjectsUsage {
	if in == nil {
		return nil
	}
	out := new(ClusterLabObjectsUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabQuotaConfig) DeepCopyInto(out *ClusterLabQuotaConfig) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Compute.DeepCopyInto(&out.Compute)
	out.Objects = in.Objects
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabQuotaConfig.
func (in *ClusterLabQuotaConfig) DeepCopy() *ClusterLabQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterLabQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabQuotaUsage) DeepCopyInto(out *ClusterLabQuotaUsage) {
	*out = *in
	in.Compute.DeepCopyInto(&out.Compute)
	in.Storage.DeepCopyInto(&out.Storage)
	out.Objects = in.Objects
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabQuotaUsage.
func (in *ClusterLabQuotaUsage) DeepCopy() *ClusterLabQuotaUsage {
	if in == nil {
		return nil
	}
	out := new(ClusterLabQuotaUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabResourceLimit) DeepCopyInto(out *ClusterLabResourceLimit) {
	*out = *in
	out.Limit = in.Limit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabResourceLimit.
func (in *ClusterLabResourceLimit) DeepCopy() *ClusterLabResourceLimit {
	if in == nil {
		return nil
	}
	out := new(ClusterLabResourceLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabSpec) DeepCopyInto(out *ClusterLabSpec) {
	*out = *in
	out.Network = in.Network
	in.Quota.DeepCopyInto(&out.Quota)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabSpec.
func (in *ClusterLabSpec) DeepCopy() *ClusterLabSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabStatus) DeepCopyInto(out *ClusterLabStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	out.InstanceCount = in.InstanceCount
	in.QuotaUsage.DeepCopyInto(&out.QuotaUsage)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabStatus.
func (in *ClusterLabStatus) DeepCopy() *ClusterLabStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterLabStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabStorageQuota) DeepCopyInto(out *ClusterLabStorageQuota) {
	*out = *in
	out.Limit = in.Limit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabStorageQuota.
func (in *ClusterLabStorageQuota) DeepCopy() *ClusterLabStorageQuota {
	if in == nil {
		return nil
	}
	out := new(ClusterLabStorageQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLabStorageUsage) DeepCopyInto(out *ClusterLabStorageUsage) {
	*out = *in
	out.Used = in.Used.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLabStorageUsage.
func (in *ClusterLabStorageUsage) DeepCopy() *ClusterLabStorageUsage {
	if in == nil {
		return nil
	}
	out := new(ClusterLabStorageUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLab) DeepCopyInto(out *InstanceLab) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLab.
func (in *InstanceLab) DeepCopy() *InstanceLab {
	if in == nil {
		return nil
	}
	out := new(InstanceLab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceLab) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabAccessEndpoint) DeepCopyInto(out *InstanceLabAccessEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabAccessEndpoint.
func (in *InstanceLabAccessEndpoint) DeepCopy() *InstanceLabAccessEndpoint {
	if in == nil {
		return nil
	}
	out := new(InstanceLabAccessEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabList) DeepCopyInto(out *InstanceLabList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceLab, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabList.
func (in *InstanceLabList) DeepCopy() *InstanceLabList {
	if in == nil {
		return nil
	}
	out := new(InstanceLabList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceLabList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabPort) DeepCopyInto(out *InstanceLabPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabPort.
func (in *InstanceLabPort) DeepCopy() *InstanceLabPort {
	if in == nil {
		return nil
	}
	out := new(InstanceLabPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabResourceLimit) DeepCopyInto(out *InstanceLabResourceLimit) {
	*out = *in
	out.Request = in.Request.DeepCopy()
	out.Limit = in.Limit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabResourceLimit.
func (in *InstanceLabResourceLimit) DeepCopy() *InstanceLabResourceLimit {
	if in == nil {
		return nil
	}
	out := new(InstanceLabResourceLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabResources) DeepCopyInto(out *InstanceLabResources) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabResources.
func (in *InstanceLabResources) DeepCopy() *InstanceLabResources {
	if in == nil {
		return nil
	}
	out := new(InstanceLabResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabSpec) DeepCopyInto(out *InstanceLabSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]InstanceLabPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabSpec.
func (in *InstanceLabSpec) DeepCopy() *InstanceLabSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceLabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabStatus) DeepCopyInto(out *InstanceLabStatus) {
	*out = *in
	if in.AccessEndpoints != nil {
		in, out := &in.AccessEndpoints, &out.AccessEndpoints
		*out = make([]InstanceLabAccessEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabStatus.
func (in *InstanceLabStatus) DeepCopy() *InstanceLabStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceLabStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceLabStorageLimit) DeepCopyInto(out *InstanceLabStorageLimit) {
	*out = *in
	out.Limit = in.Limit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceLabStorageLimit.
func (in *InstanceLabStorageLimit) DeepCopy() *InstanceLabStorageLimit {
	if in == nil {
		return nil
	}
	out := new(InstanceLabStorageLimit)
	in.DeepCopyInto(out)
	return out
}
