---
# ==============================================================================
# GENERAL CLUSTER VARIABLES (Tương tự group_vars/all/all.yml trong Kubespray)
# ==============================================================================

# Nền tảng phân phối Kubernetes mặc định ('kubeadm' hoặc 'k3s'):
kubernetes_distro: "kubeadm"

# Cấu hình phiên bản và mạng cho Kubeadm (Mặc định):
kubeadm_k8s_version: "v1.35.0"
kubeadm_pod_subnet: "192.168.0.0/16" # Sửa thành 10.244.0.0/16 nếu dải mạng bị trùng LAN host

# Cấu hình cho K3s (Tùy chọn khi truyền -e kubernetes_distro=k3s):
k3s_version: "v1.32.5+k3s1"
kubeconfig_remote: "/etc/rancher/k3s/k3s.yaml"
containerd_dir: "/var/lib/rancher/k3s/agent/etc/containerd"
containerd_template: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"

# Các module hạt nhân hệ điều hành hỗ trợ cho máy ảo Pod (Docker-in-Docker / Sysbox):
enable_shiftfs: true
enable_lxcfs: true
