---
common_enable_shiftfs: true
common_enable_lxcfs: true
common_containerd_dir: "/var/lib/rancher/k3s/agent/etc/containerd"
common_containerd_template: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
