---
sysbox_manifest_url: "https://raw.githubusercontent.com/nestybox/sysbox/master/sysbox-k8s-manifests/sysbox-install.yaml"
sysbox_kubectl: "{{ 'k3s kubectl' if (kubernetes_distro | default('kubeadm')) == 'k3s' else 'kubectl' }}"
